###################################################
#             __  ___     ___  _______
#	     /  |/  /_ __/ _ \/ __<  /
#	    / /|_/ / // / ___/\ \ / /
#	   /_/  /_/\_, /_/  /___//_/
#		  /___/
#
#            POWERED BY: R14N 64RC14
#     GitHub: https://github.com/RyanGarccia
#           Youtube: Society Anonymous
#
###################################################
##################### My PS1 ######################
# Chamando o Script para ser iniciado...
#
cd && cd ~/MyPS1 && sh MyPS1.sh
#
# Script iniciado...
